#!/usr/bin/env bash

# like cd but fuzzy
cf() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir" || return
}

# sync caravan repo
caravan-push() {
    git add .
    git commit -a -m "$1"
    git push
  }

caravan-sync() {
    cd ~/.config/nixpkgs
    git checkout main
    git pull origin main
    home-manager switch
}
