#!/usr/bin/env bash

# like cd but fuzzy
cf() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir" || return
}

# sync caravan repo
push-nix() {
    cd ~/.config/nixpkgs
    git add .
    git commit -a -m "$1"
    git push
    cd -
  }

sync-nix() {
    cd ~/.config/nixpkgs
    git add .
    git stash
    git checkout main
    git pull origin main
    git stash pop
    home-manager switch
    push-nix "sync-nix performed on $(date)"
    cd -
}
