window:
  decorations: buttonless

  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  startup_mode: Maximized

  # Padding on the edge of the window (this is not empty space on the desktop)
  padding:
    x: 4
    y: 4

font:
  normal:
    family: JetBrainsMono Nerd Font

  # Point size of the font
  size: 16.0

shell:
  program: /Users/tom/.nix-profile/bin/zsh 
  args:
    - -c
    - cd ~/Git && exec zsh

key_bindings:
  - { key: Key3,     mods: Alt,     chars: "#"                        }
