window:
  opacity: 0.82
  decorations: buttonless

  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  startup_mode: Maximized

  # Padding on the edge of the window (this is not empty space on the desktop)
  padding:
    x: 10
    y: 10

font:
  normal:
    family: JetBrainsMono Nerd Font

  # Point size of the font
  size: 16.0

shell:
  program: /Users/tom/.nix-profile/bin/zsh
  args:
    - -c
    - cd ~/Git && exec zsh

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: '0x282828'
    # soft contrast: background = '0x32302f'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xcc241d'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'

key_bindings:
  - { key: Key3,     mods: Alt,     chars: "\x23"                        }
