name: Cron

on:
  schedule:
  - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs: {}

jobs:
  sync:
    name: run
    runs-on: ubuntu-latest
    steps:

    - name: Run
      run: |
        echo "hello world"
